spring.application.name=ms-gateway
server.port=8080

# ms-auth
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

# ms-categoria
spring.cloud.gateway.server.webmvc.routes[1].id=ms-categoria
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8094
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v2/categorias/**

# ms-producto
spring.cloud.gateway.server.webmvc.routes[2].id=ms-producto
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v2/productos/**

# ms-proveedor
spring.cloud.gateway.server.webmvc.routes[3].id=ms-proveedor
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v2/proveedores/**

# ms-inventario
spring.cloud.gateway.server.webmvc.routes[4].id=ms-inventario
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v2/inventarios/**

# ms-cupon-descuento
spring.cloud.gateway.server.webmvc.routes[5].id=ms-cupon-descuento
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v2/cupones/**