spring.application.name=ms-reserva
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/ms-reserva
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=u1tocZpNfuILDtiuMYperfume1u4pKL9D