spring.application.name=ms-usuario
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/ms-usuario
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true